name: ColorCodeViewer
author: 真心
version: 1.0-beta
description: §a一条指令查看颜色代码表 §cGit：https://gitee.com/QianyeGroup/ColorCodeViewer
main: cn.iqianye.MinecraftPlugins.ColorCodeViewer.Main
commands:
  colorcodeviewer:           
    description: §a使用此指令可查看颜色代码表
    usage: /colorcodeviewer
    permission: colorcodeviewer.use
    permission-message: §c您没有使用此命令的权限！
  ccv:
    description: §a使用此指令可查看颜色代码表
    usage: /ccv
    permission: colorcodeviewer.use
    permission-message: §c您没有使用此命令的权限！
  color:
    description: §a使用此指令可查看颜色代码表
    usage: /color
    permission: colorcodeviewer.use
    permission-message: §c您没有使用此命令的权限！
  colorcode:
    description: §a使用此指令可查看颜色代码表
    usage: /colorcode
    permission: colorcodeviewer.use
    permission-message: §c您没有使用此命令的权限！
permissions: 
  colorcodeviewer.use: 
    default: true
    description: §a是否可以查看颜色代码